# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20160718_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
    ]
