# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_remove_subscriber_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubReddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=21, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='send_hour',
            field=models.IntegerField(choices=[(0, '12:00 AM'), (1, '1:00 AM'), (2, '2:00 AM'), (3, '3:00 AM'), (4, '4:00 AM'), (5, '5:00 AM'), (6, '6:00 AM'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM'), (21, '9:00 PM'), (22, '10:00 PM'), (23, '11:00 PM')], default=8),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subreddits',
            field=models.ManyToManyField(related_name='subscribers', to='subscribers.SubReddit'),
        ),
    ]
