# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_auto_20160719_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_hash',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
